name: Update data (daily)
on:
  schedule:
    - cron: "15 3 * * *"   # daily at 03:15 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Run updater
        env:
          SOURCE_JSON_URL: ${{ secrets.SOURCE_JSON_URL }}
          SOURCE_CSV_URL:  ${{ secrets.SOURCE_CSV_URL }}
        run: node scripts/update-data.mjs
      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/data.json data/backups || true
          if git commit -m "chore(data): daily update"; then
            git push
          else
            echo "No changes to commit."